### ISSUE TITLE
Auth headers not set on requests if proxy is set. 

### ISSUE THREAD

**Issue by alanquigley** [nolanlawson/pouchdb-load#16]
db.info().then(function (info) {
        var src = new db.constructor(opts.proxy, opts);
        var target = new db.constructor(info.db_name, opts);
        var replIdOpts = {};
        if (opts.filter) {
          replIdOpts.filter = opts.filter;
        }

The following code changes seem to work.

**Comment by nolanlawson** [comment]
Hm, yeah, that's not quite right, though, because it's applying the opts to both the local database and the remote one. Could have unintended results if you are replicating between two remote databases. Tricky problem...

**Comment by nolanlawson** [comment]
Ah, okay, I see that I do support `ajax` options per the documentation. So the fix should be to copy over `ajax` to both, and also using the database's native `db.__opts`. I'll try to fix this soon.

**Comment by nolanlawson** [comment]
Can you try https://github.com/nolanlawson/pouchdb-load/pull/17 and let me know if it works for you?

**Comment by alanquigley** [comment]
Awesome, thanks.

I've also noticed post load, I'm getting a large number of these errors, and its taking roughly 15 seconds to process the pouch-api requests, should the proxy be circumventing this?

pouchdb:api project_14b54b108d0-mrview-temp +1ms get error CustomPouchError {status: 404, name: "not_found", message: "missing", error: true, toString: function}

**Comment by alanquigley** [comment]
#17 seems to fix the auth header issue.

**Comment by nolanlawson** [comment]
Cool, that's good enough for me. :)

**Comment by nolanlawson** [comment]
1.3.4

**Comment by alanquigley** [comment]
Thank you.
