### ISSUE TITLE
AMD Support

### ISSUE THREAD

**Issue by ddouglascarr** [nolanlawson/pouchdb-load#18]
For require.js, etc.

**Comment by nolanlawson** [comment]
See comment in https://github.com/nolanlawson/pouchdb-load/pull/20, and again, sorry to be a jerk about this.

**Comment by nolanlawson** [comment]
Also see https://github.com/nolanlawson/pouchdb-all-dbs/issues/12 for instructions about how to use these plugins with AMD/UMD.
