### ISSUE TITLE
no data loaded

### ISSUE THREAD

**Issue by barbalex** [nolanlawson/pouchdb-load#30]
Warning: noob error probable!

My problem is that no data is loaded.

I built the dump using pouchdb-dump-cli. You can see a replicated copy of it here: http://46.101.166.244:5984/artendb/ae_objekte/ae_objekte.txt
It is a 340 MB file.

(the app is a CouchApp - so in order to serve the dump I attached it to a document - could there be something wrong with that?)

in app.js I set up the db like this:

    app.extend({
      init () {
        this.localDb = new PouchDB('ae', function (error) {
          if (error) return console.log('error initializing local pouch ae:', error)
        })
      }
    })
    app.init()

In actions.js I'm setting up like this:

    import PouchDB from 'pouchdb'
    import pouchdbLoad from 'pouchdb-load'
    PouchDB.plugin(pouchdbLoad)

I then do:

    const url = 'http://localhost:5984/artendb/ae_objekte/ae_objekte.txt'
    app.localDb.load(url)

or:

    function filterFunction (doc) {
      if (doc.Typ && doc.Typ === 'Objekt') return true
      return false
    }

    const url = 'http://localhost:5984/artendb/ae_objekte/ae_objekte.txt'
    const couchUrl = 'http://localhost:5984/artendb'
    app.localDb.load(url, {
          proxy: couchUrl,
          filter: filterFunction
        })

No error occurs. But localDb remains empty.

I have also tried requesting the dump first using superagent (https://github.com/visionmedia/superagent):

    request
      .get('http://localhost:5984/artendb/ae_objekte/ae_objekte.txt')
      .end(function (error, res) {
        // res.body is null!
      })

So no data arrived in the body?? This smells like some very nooby mistake to me.

I have added normal replication to take over after the load finished. This works - but ALL docs are replicated. I first thought it was because I had made a mistake with the proxy or the filter but it seems like it is because loading didn't work.

**Comment by nolanlawson** [comment]
Did you try putting a `.then()` and a `.catch()` on your promise? If you just call `db.load()` it returns a promise, and any errors will be swallowed. I wrote [more about promises here](http://pouchdb.com/2015/05/18/we-have-a-problem-with-promises.html) if that helps.

Did you check the network tab in the Chrome Dev Tools? Maybe CORS is not enabled on your server.

You can also try fetching your file through normal AJAX and then you can `load()` the string directly.

**Comment by barbalex** [comment]
yes, I did put .then and catch. Here is more of the code:

    Actions.loadPouchFromRemote.listen(function () {
      console.log('Actions.loadPouchFromRemote active')
      // get all items
      const couchUrl = getCouchUrl()
      const url = couchUrl + '/ae_objekte/ae_objekte.txt'
      app.localDb.load(url, {
        proxy: couchUrl,
        filter: objectFilterFunction
      })
      .then(function () {
        // let regular replication catch up if objects have changed since dump was created
        return app.localDb.replicate.from(app.remoteDb)
      })
      .then(function () {
        Actions.loadPouchFromRemote.completed()
      })
      .catch(function (error) {
        console.log('Actions.loadPouchFromRemote, replication error:', error)
      })
    })

CORS is enabled.

I tried fetching the file through AJAX (using superagent) but got no data:

    request
      .get('http://localhost:5984/artendb/ae_objekte/ae_objekte.txt')
      .end(function (error, res) {
        // res.body is null!
      })

I feel like this is the smelly fact.

**Comment by barbalex** [comment]
meanwhile I found out this does work with files up to 340 MB but it still does not work with the original file which is not 340 but rather about 700 MB big (that is the only difference to the other files, as they are extracts of the big one). I guess I will have to split it up into smaller files. 

Closing the issue as it does work with smaller files and I guess it is not a good idea to load 700 MB in one chunk into the browser

**Comment by barbalex** [comment]
I use the `--split` option from pouchdb-dump-cli now to produce files of approximately 5 MB size. This now works very nice

Thanks for great tools!

**Comment by nolanlawson** [comment]
Great, happy to hear it! :)
