### ISSUE TITLE
how to write checkpoints when loading splitted dump

### ISSUE THREAD

**Issue by barbalex** [nolanlawson/pouchdb-load#31]
My code loads a split dump like this:

    const gruppeString = gruppe === 'Lebensräume' ? 'lr' : (gruppe === 'Macromycetes' ? 'pilze' : gruppe.toLowerCase())
    app.remoteDb.get('ae-' + gruppeString)
      .then(function (doc) {
        return _.keys(doc._attachments)
      })
      .then(function (attachments) {
        let series = PouchDB.utils.Promise.resolve()
        attachments.forEach(function (fileName) {
          series = series.then(function () {
            const couchUrl = getCouchUrl()  // is: http://localhost:5984/artendb (local dev) or http://arteigenschaften.ch/artendb (production, untested yet)
            const loadUrl = couchUrl + '/ae-' + gruppeString + '/' + fileName
            // TODO: looks like no checkpoint is set, so following replication takes forever
            return app.localDb.load(loadUrl, {proxy: couchUrl})
          })
        })
        series.then(function () {
          resolve(true)
        })

Real code here: https://github.com/barbalex/ae/blob/master/src/modules/loadGroupFromRemote.js

When the promise resolves, replication is started for the loaded subset of docs:

    app.localDb.replicate.from(app.remoteDb, {
      filter: function (doc) {
        return (doc.Gruppe && doc.Gruppe === gruppe)
      }
    })

Real code here: https://github.com/barbalex/ae/blob/master/src/actions.js#L98-L102

The problem is: A checkpoint was not written, or so it seems, because pouchdb starts thousands of changes requests to the remoteDb. 

After this replication the checkpoint was written thought: if I start replication a second time (manually) it finishes after only two requests to the remoteDb.

Am I doing something wrong?

Or does the proxy setting only work when a dump was not split?

I do see that the split files are loaded from last to first. So if pouchdb overwrites the checkpoint every time it loads one of the split files, there will be a checkpoint but most of the replication will still happen.

Update: I changed the sorting of the split files. The one with the last docs is now loaded last. Replication still takes forever.

**Comment by nolanlawson** [comment]
Looking at your code, it seems like the issue is that you are not providing a `proxy` option to the `load()` request. If you don't, then replication will start from scratch after you've `load()`ed all the files. (Although yes you are right that the order matters for checkpoing writing; you should load the last one last.)

As a working example, you can look at http://npm-browser.com, which loads may large files in sequence and then switches to regular replication with a remote CouchDB. [Here is the code for the loading operation](https://github.com/pouchdb/npm-browser/blob/41a57412d020a8a8acdf91d11deeb113ca39df0d/scripts/services/pouch-service.js#L73-L105).

**Comment by barbalex** [comment]
is it not included in this line here?: https://github.com/barbalex/ae/blob/master/src/modules/loadGroupFromRemote.js#L33

**Comment by barbalex** [comment]
Hey, seems like you looking solved the issue ;-)

Without changing any code it suddenly works. Maybe caching played a trick?

Anyway: I now write the checkpoint only when loading the last dump of split files: https://github.com/barbalex/ae/blob/master/src/modules/loadGroupFromRemote.js#L35-L39

Sorry for bugging you!

**Comment by nolanlawson** [comment]
Happy it works. :)
