### ISSUE TITLE
Error loading dump with filter view

### ISSUE THREAD

**Issue by Coniglioz** [nolanlawson/pouchdb-load#41]
The error is:
**TypeError: Cannot read property 'toString' of undefined at generateReplicationId**
on line 2272 of pouchdb.load.js

This happens when you load the dump using a view as filter, for example:
```javascript
db.load('http://example.com/my-dump-file.txt', {
  proxy: 'http://mysite.com/mydb',
  filter: '_view',
  view: 'mydesign/myview'
})
```

**Suggested solution**
Complete the "replIdOpts" object passed to "genReplicationId" on line 67 by adding the "view" attribute.
```javascript
...
if (opts.view) {
  replIdOpts.view = opts.view;
}
...
```

**Comment by nolanlawson** [comment]
Yup, your fix looks correct to me. Needs to be added to [these lines](https://github.com/nolanlawson/pouchdb-load/blob/a68a7867b5b2068100f939d374b58b03f21b8635/lib/index.js#L59-L64) and also needs [another test](https://github.com/nolanlawson/pouchdb-load/blob/a68a7867b5b2068100f939d374b58b03f21b8635/test/test.js#L315-L380). Want to contribute it? :D

**Comment by Coniglioz** [comment]
Ok! I'll do it :D

**Comment by nolanlawson** [comment]
a99028a400584b480a1adabe707bad9a50d07d10
