### ISSUE TITLE
Large size using browserify

### ISSUE THREAD

**Issue by bmihelac** [nolanlawson/pouchdb-load#50]
Just requiring pouchdb and pouchdb-load in a script and running browserify yields 2.1MB file.

Without pouchdb-load file size is 368K.

I created small repo to reproduce it:

https://github.com/bmihelac/test-pouchdb-load

**Comment by nolanlawson** [comment]
Fixed in 527c3e3e56120c7d0e9b524eee74e1501871b542, the bundle size is now 17k min+gzipped or 126k raw.

**Comment by nolanlawson** [comment]
published in pouchdb-load 1.4.6, cheers

**Comment by bmihelac** [comment]
Tested it and it work as expected. Thanks a lot.
