### ISSUE TITLE
TypeError: readableStream.pipe is not a function

### ISSUE THREAD

**Issue by aaronstephenson** [nolanlawson/pouchdb-load#58]
I'm trying to use pouchdb with Ionic2. So far, everything seems to be working fine except pouchdb-load. I'm trying to [load](https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html) in a database from a dump file
([SEWRPC_ROOTRIVER@RACINE_2017-04-03.txt](https://github.com/nolanlawson/pouchdb-load/files/900619/SEWRPC_ROOTRIVER.RACINE_2017-04-03.txt))
 (previously exported to a text file using pouchdb-replication-stream and memory-stream, per [your example](https://github.com/nolanlawson/pouchdb-replication-stream#dumping-to-a-string)).

Every time I run my app, the first time _db.load() runs, I get `TypeError: readableStream.pipe is not a function` when the app gets to the line with `this._db.load(data)`; all subsequent runs (such as when navigating off the page then returning to the page and reading the text file again) succeed, and I see the data as expected. Any help or suggestions would be greatly appreciated!

_Failure on first run:_
![capture1](https://cloud.githubusercontent.com/assets/8713712/24723555/a1d09204-1a0d-11e7-905d-b40058841505.png)

_Success on subsequent runs:_
![capture2](https://cloud.githubusercontent.com/assets/8713712/24723560/a4874cb8-1a0d-11e7-98b3-62fda8b068dd.png)

**Code snippets:**

_sample-list.ts:_
```
loadSamples(fileInput: any){
      let self = this;
      let selectedFiles = <Array<File>> fileInput.target.files || fileInput.dataTransfer.files;
      let reader = new FileReader();
      reader.onload = function(e) {
            self._sampleService.loadDB(reader.result);
      };
      reader.readAsBinaryString(selectedFiles[0]);
}
```

_sample.service.ts_:
```
import {Injectable}     from '@angular/core';
import PouchDB from 'pouchdb';
import PouchDBLoad from 'pouchdb-load';

@Injectable()
export class SampleService{
      private _db;

      constructor() {
            PouchDB.plugin(PouchDBLoad);
            this._db = new PouchDB('samples');
      }

      loadDB(data) {
            this._db.load(data).then(response => {
                  console.log("load done");
            }).catch( error => {
                  console.log(error);
            });
}
```

**Environment:**

- Windows 7
- Chrome 57
- Firefox 52
- Node 6.10.0
- NPM 3.10.10
- Typescript 2.2.2
- Angular 2.2.1
- Ionic 2.0.0
- pouchdb 6.1.0
- pouchdb-load 1.4.6

**Comment by aaronstephenson** [comment]
I found the cause of the problem: pouchdb-load was conflicting with pouchdb-replication-stream, exactly as you noted [here](https://github.com/nolanlawson/pouchdb-replication-stream#warning-when-using-pouchdb-load). I had read your warning earlier, but didn't give it much thought because I wasn't using the replication stream library in this particular file (sample.service.ts), only in other files... but perhaps just using it anywhere in the app causes a conflict?

Would you considering adding a bit more detail (specifically, what the conflict looks like, perhaps mentioning the expected error?) to your warning in the pouchdb-replication-stream README, and explicitly mentioning it in the pouchdb-load README, to prevent potential head-slam-table moments for future users who might make the same wrong assumption I did.

Thanks for your work on this project! I really appreciate the effort you and your fellow FOSS maintainers put in for the benefit of the community.

**Comment by nolanlawson** [comment]
Sorry for the trouble! Yes, a PR to update the README on this repo to mention the issue would be welcome :)
